### ISSUE TITLE
`deepagents` 0.0.12rc2: `async_create_deep_agent` function removed from `__init__.py` causing ImportError

### ISSUE THREAD

**Issue by bart0401** [langchain-ai/langchain#33548]
### Checked other resources

- [x] This is a bug, not a usage question.
- [x] I added a clear and descriptive title that summarizes this issue.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
- [x] This is not related to the langchain-community package.
- [x] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [x] I posted a self-contained, minimal, reproducible example. A maintainer can copy it and run it AS IS.

### Works in 0.0.12rc1 ✅
```python
# DeepAgents 0.0.12rc1
from deepagents import async_create_deep_agent

# Successfully imports
print(async_create_deep_agent)  # <function async_create_deep_agent at 0x...>
```

### Breaks in 0.0.12rc2 ❌
```python
# DeepAgents 0.0.12rc2
from deepagents import async_create_deep_agent

# ImportError: cannot import name 'async_create_deep_agent' from 'deepagents'
```

## Error Message and Stack Trace

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'async_create_deep_agent' from 'deepagents' (/path/to/site-packages/deepagents/__init__.py)
Did you mean: 'create_deep_agent'?
```

### What is the problem?

In DeepAgents **0.0.12rc2**, the `async_create_deep_agent` function has been **removed from `__init__.py`** exports, causing ImportError for existing code that relies on this function.

#### 0.0.12rc1 (Working) ✅

**`__init__.py` exports:**
```python
from deepagents.graph import create_deep_agent, async_create_deep_agent
from deepagents.middleware import PlanningMiddleware, FilesystemMiddleware, SubAgentMiddleware
from deepagents.state import DeepAgentState
from deepagents.types import SubAgent, CustomSubAgent
from deepagents.model import get_default_model
```

**`graph.py` functions:**
```python
def create_deep_agent(...):  # Line 66
    ...

def async_create_deep_agent(...):  # Line 114
    ...
```

#### 0.0.12rc2 (Broken) ❌

**`__init__.py` exports:**
```python
from deepagents.graph import create_deep_agent  # async_create_deep_agent MISSING!
from deepagents.middleware.filesystem import FilesystemMiddleware
from deepagents.middleware.subagents import CompiledSubAgent, SubAgent, SubAgentMiddleware

__all__ = ["CompiledSubAgent", "FilesystemMiddleware", "SubAgent", "SubAgentMiddleware", "create_deep_agent"]
```

**`graph.py` functions:**
```python
def create_deep_agent(...):  # Line 37
    # async_create_deep_agent function COMPLETELY REMOVED!
```

### System Info

```
Package: deepagents
Version (Broken): 0.0.12rc2
Version (Working): 0.0.12rc1

Python: 3.12.3
Platform: linux

Dependencies:
- langgraph>=1.0.0a4
- langchain-anthropic>=1.0.0a4
- langchain>=1.0.0a15
- langgraph-prebuilt>=0.7.0a2
- langchain-core>=1.0.0a6
```

**Comment by bart0401** [comment]
https://github.com/langchain-ai/deepagents/issues/174

Move the issue to deep agents/issues and close it.
