### ISSUE TITLE
Getting Import Error Basemodel

### ISSUE THREAD

**Issue by alijavaidistar** [langchain-ai/langchain#5795]
### System Info

Hello,

I am getting an error in import

Here are my import statements:
from llama_index import SimpleDirectoryReader, GPTListIndex, readers, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain import OpenAI
import sys
import os
from IPython.display import Markdown, display

Here is the error:
from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\ali\PycharmProjects\GeoAnalyticsFeatures\venv\lib\site-packages\langchain\schema.py)

What I have tried:
upgrade PIP
upgrade lama

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hello,

I am getting an error in import

Here are my import statements:
from llama_index import SimpleDirectoryReader, GPTListIndex, readers, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain import OpenAI
import sys
import os
from IPython.display import Markdown, display

Here is the error:
from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\ali\PycharmProjects\GeoAnalyticsFeatures\venv\lib\site-packages\langchain\schema.py)

What I have tried:
upgrade PIP
upgrade lama

### Expected behavior

Hello,

I have followed all the instructions in the comments above but still coming the same issue:

Here are my import statements:
from llama_index import SimpleDirectoryReader, GPTListIndex, readers, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain import OpenAI
import sys
import os
from IPython.display import Markdown, display

Here is the error:
from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\ali\PycharmProjects\GeoAnalyticsFeatures\venv\lib\site-packages\langchain\schema.py)

What I have tried:
upgrade PIP
upgrade lama

**Comment by KeshavSingh29** [comment]
This is not an issue. 
Just look at the error and check the schema.py file. `BaseLanguageModel` class is not defined there thats why the error. 
Please check the error code and do some digging before starting an issue. 
Upgrade your langchain also just in case.

**Comment by alijavaidistar** [comment]
Hello @KeshavSingh29 

I have already looked into the scheme file and BaseLanguageModel exists in file.  My pip, langchain, and everything else possible that I could update, I have done it already.

**Comment by KeshavSingh29** [comment]
@alijavaidistar 
My bad. 
It seems to be either the case of langchain version or env issue. 
Can you share which version of langchain you are using? 
I'm using `langchain==0.0.146` and with that there are no errors in importing `BaseLanguageModel`. 
However, if you install directly from git repository, the `BaseLanguageModel` class is not in schema.py.

**Comment by ajhaslam** [comment]
I was seeing the same issues. I was trying to work with `langchain==0.0.195` and was encountering a similar import error regarding the `BaseLanguageModel` 
Reverting back to `langchain==0.0.146` stopped the issue.
