### ISSUE TITLE
langchain_openai>=0.1.21 not compatible with AzureChatOpenAI and response_format={"type": "json_object"}

### ISSUE THREAD

**Issue by felixkrones** [langchain-ai/langchain#25485]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_openai import AzureChatOpenAI, ChatOpenAI

model_chat = ChatOpenAI(
    base_url="", 
    api_key="", 
    model="gpt-4o-2024-05-13",
)

model_azure = AzureChatOpenAI(
    openai_api_version="2024-06-01",
    azure_deployment="gpt-4o-2024-05-13",
)

response_chat = model_chat.invoke(
    "Tell me a story but return it as a json object.",
    response_format={"type": "json_object"},
)
response_azure = model_azure.invoke(
    "Tell me a story but return it as a json object.",
    response_format={"type": "json_object"},
)
```

### Error Message and Stack Trace (if applicable)

`AttributeError: 'NoneType' object has no attribute 'beta'`

### Description

* If I use `AzureChatOpenAI` together with `response_format={"type": "json_object"}` the above error occurs.
* It works fine with `langchain_openai==0.1.20`

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  # 1 SMP Tue Feb 27 17:09:32 UTC 2024
> Python Version:  3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

Package Information
-------------------
> langchain_core: 0.2.32
> langchain: 0.2.14
> langchain_community: 0.2.12
> langsmith: 0.1.94
> langchain_openai: 0.1.21
> langchain_text_splitters: 0.2.1

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.0
> async-timeout: Installed. No version info available.
> beautifulsoup4: 4.12.3
> dataclasses-json: 0.6.7
> jsonpatch: 1.33
> lxml: 5.2.2
> numpy: 1.26.4
> openai: 1.40.6
> orjson: 3.10.6
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.1
> requests: 2.32.3
> SQLAlchemy: 2.0.31
> tenacity: 8.3.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by ccurme** [comment]
Thank you for reporting this. Closing as duplicated with https://github.com/langchain-ai/langchain/issues/25479.
