### ISSUE TITLE
[2024-05-31 11:06:20,219: WARNING] langchain_core.callbacks.manager: Error in LangChainTracer.on_chain_end callback: AttributeError("'NoneType' object has no attribute 'append'")

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langchain#22353]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I don't have a MRE, but better to tell you what I know than nothing at all: after updating to latest 0.2.x from 0.1.x, I started having this warning. It comes from `lanchain_core/tracers/base.py:399`. I noticed that `chain_run` is of class `RunTree` rather than `Run`, it looks like `self.run_map` in that function contains a mix of `Run` and `RunTree` objects, of which only the `Run` objects have an `events` defined?

![image](https://github.com/langchain-ai/langchain/assets/8631181/f068df53-8246-40ab-80f1-17224bce0858)

### Description

See above

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 11:49:30 +0000
> Python Version:  3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]

Package Information
-------------------
> langchain_core: 0.2.3
> langchain: 0.2.1
> langchain_community: 0.2.1
> langsmith: 0.1.65
> langchain_cli: 0.0.24
> langchain_cohere: 0.1.5
> langchain_mongodb: 0.1.5
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.17
> langgraph: 0.0.59
> langserve: 0.2.1

**Comment by lesong36** [comment]
same here.
Error in LangChainTracer.on_chain_end callback: AttributeError("'NoneType' object has no attribute 'append'")

tensorflow: 2.16.1
torch: 2.3.0
langchain: 0.2.1
langchain-core: 0.2.3
langgraph: 0.0.59
langchain-community: 0.2.1
langchain-experimental: 0.0.59
langchain-openai: 0.1.8
langserve: 0.2.1
langchain-cli: 0.0.24
langsmith: 0.1.65
openai: 1.30.5
cohere: 5.5.4
huggingface-hub: 0.23.2
transformers: 4.39.3
yfiles_jupyter_graphs: 1.6.2
httpx: 0.27.0
pydantic: 2.7.1

**Comment by keenborder786** [comment]
okay can you please share the code of your chain where you are using this tracer?

**Comment by ldorigo** [comment]
It's a large application with a large amount of chains and due to the async nature of langchain (and the way the library is structured) it's very difficult to know which particular chain is causing problems, but I start the tracing with:

```python
        with tracing_v2_enabled(settings.LANGCHAIN_PROJECT, client=LANGSMITH_CLIENT) as _:
            ...
            with callbacks.collect_runs() as cb:
                async for event in self.astream_events(...)
```

Not sure if this helps, if you have specific questions I can try to answer them. 

Note that I found this is caused by the latest langchain-core 0.2.3, I fixed the version to 0.2.2 and the error doesn't happen there.

**Comment by supernitin** [comment]
I'm facing the same issue. I also was able to resolve it by fixing langchain-core version to 0.2.2.

**Comment by hinthornw** [comment]
Thanks for raising - looks like my testing for this change was insufficient - will triage

**Comment by hinthornw** [comment]
@ldorigo is this purely langchain code? Or are you mixing `@traceable` or similar logic within it?

**Comment by hinthornw** [comment]
Will re-open until it is confirmed as fixed
