### ISSUE TITLE
NotImplementedError: WebBaseLoader does not implement lazy_load()

### ISSUE THREAD

**Issue by F2EVarMan** [langchain-ai/langchain#6704]
### Issue you'd like to raise.

when i use RecusiveUrlLoader , 
NotImplementedError: WebBaseLoader does not implement lazy_load()

![image](https://github.com/hwchase17/langchain/assets/10355060/2d1686e7-de7f-412b-a9f4-1024ec666281)

**Comment by ptah23** [comment]
I got this in a notebook when i upgraded langchain from 203. restarting the kernel seems to work
