### ISSUE TITLE
NotEnoughElementsException

### ISSUE THREAD

**Issue by mnask** [langchain-ai/langchain#5714]
im getting this error 

AttributeError: module 'chromadb.errors' has no attribute 'NotEnoughElementsException'

here my code 

```
persist_directory = 'vectorstore'
embeddings = OpenAIEmbeddings()
vectorstore = Chroma(persist_directory=persist_directory, embedding_function=embeddings)
chat_history = []
vectorstore.add_texts(["text text text"])
llm = ChatOpenAI(temperature=0.2)

qa = ConversationalRetrievalChain.from_llm(
    llm,
    vectorstore.as_retriever(),
)  
```

does it mean my vectorstore is damaged ?

**Comment by Svn-Sp** [comment]
No, the problem is in langchains code. It's this line in vectorstores/chroma.py:
`except chromadb.errors.NotEnoughElementsException:`


This doesn't fit to how Exceptions from Chroma==0.3.26 (latest) have to be imported.
As a temporary fix you can downgrade to Chroma==0.3.25, if I find enough time I'll open a PR to fix this issue later today

**Comment by pranathtechnocraft** [comment]
@Svn-Sp I'm on chromadb==0.3.25 and I get the same error.

**Comment by cloudcerebro** [comment]
I'm on chromadb==0.3.25 and getting the same error.

**Comment by AntoonGa** [comment]
Hi,

I'm trying to score all chunks from a vector db containking "k" chunks.
I'd like the similarity score to return all documents with their respective score.
Doing this:
`vectordb = Chroma(persist_directory=directory, embedding_function=embeddings)
k_max = len(vectordb['documents'])
scored_chunks = vectordb.similarity_search_with_score(query=user_query, distance_metric="cos", k = k_max)
`

I am getting the same error

`AttributeError: module 'chromadb.errors' has no attribute 'NotEnoughElementsException'`

when recuding k by a small factor the code works okay. Can somebody give me a work-around to score all my chunks ?

Im on chromadb  0.3.26

**Comment by lijingquan1** [comment]
The problem is in langchains code and it is gone after upgrading the Langchain from 0.0.191 to 0.0.219.
