### ISSUE TITLE
cannot import name 'BaseOutputParser' from 'langchain.schema'

### ISSUE THREAD

**Issue by diman82** [langchain-ai/langchain#1936]
UJsing py 3.11 (works in py 3.10) with latest (0.4.36) version.

Traceback:
```
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "D:\dev\openai-pr-summarization\main.py", line 9, in <module>
    from engine.llama import LlamaEngine
File "D:\dev\openai-pr-summarization\engine\llama.py", line 3, in <module>
    from llama_index import GPTSimpleVectorIndex, Document
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\indices\keyword_table\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\indices\keyword_table\base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\indices\base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\indices\prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 6, in <module>
    from llama_index.llm_predictor.base import (  # noqa: F401
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\llm_predictor\__init__.py", line 4, in <module>
    from llama_index.llm_predictor.base import LLMPredictor
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\llm_predictor\base.py", line 15, in <module>
    from llama_index.prompts.base import Prompt
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\prompts\__init__.py", line 3, in <module>
    from llama_index.prompts.base import Prompt
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\prompts\base.py", line 11, in <module>
    from llama_index.output_parsers.base import BaseOutputParser
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\output_parsers\__init__.py", line 4, in <module>
    from llama_index.output_parsers.langchain import LangchainOutputParser
File "C:\Users\diman\mambaforge\envs\py311\Lib\site-packages\llama_index\output_parsers\langchain.py", line 6, in <module>
    from langchain.schema import BaseOutputParser as LCOutputParser
```

**Comment by Krumil** [comment]
Same here

**Comment by stepanogil** [comment]
samedt. im on python 3.10.5. what a bummer

**Comment by Maxim-Filimonov** [comment]
same problem with 
`from llama_index import download_loader`
on 3.9 fails - works on 3.10

**Comment by sisyphusSmiling** [comment]
Running on python 3.10.0 and importing from `llama_index`. Any guidance on minor version compatibility?

**Comment by scott-svmx** [comment]
> Running on python 3.10.0 and importing from `llama_index`. Any guidance on minor version compatibility?

It works for me with Python 3.10.11.  Earlier I was getting the error with Python 3.9.9
