### ISSUE TITLE
 ImportError: cannot import name 'Vector' from 'azure.search.documents.models'

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#16351]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

This code works with langchain 0.1.0 and Azure Search Documents 11.4b9

However WIth Azure Search Documents 11.4.0 I get the error:  ImportError: cannot import name 'Vector' from 'azure.search.documents.models'

```
  with callbacks.collect_runs() as cb:

        embeddings = AzureOpenAIEmbeddings(
            azure_deployment=OPENAI_EMBEDDING_DEPLOYMENT_NAME,
            openai_api_version="2023-05-15",
        )

        # Init vector store
        vector_store: AzureSearch = AzureSearch(
            azure_search_endpoint=SEARCH_SERVICE_ENPOINT,
            azure_search_key=SEARCH_SERVICE_ADMIN_KEY,
            index_name=index_name,
            embedding_function=embeddings.embed_query,
        )
    
        llm = AzureChatOpenAI(
            azure_deployment=OPENAI_DEPLOYMENT_ENDPOINT1, openai_api_version="2023-05-15"
        )

        # Should take `chat_history` and `question` as input variables.
        condense_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question. If you do not know the answer reply with 'I am sorry'.
        Chat History:
        {chat_history}
        Follow Up Input: {question}
        Standalone question:"""

        CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(condense_template)

        question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)

        prompt_template = """Use the following pieces of context to answer the question at the end.  Try to answer in a structured way. Write your answer in HTML format but do not include ```html ```. Put words in bold that directly answer your question.
        If you don't know the answer, just say 'I am sorry I dont know the answer to this question or you dont have access to the files needed to answer the question.' Don't try to make up an answer.

        {context}

     
        Question: {question}.
        """

        PROMPT = PromptTemplate(
            template=prompt_template, input_variables=["context", "question"]
        )

        doc_chain = load_qa_chain(llm, chain_type="stuff", prompt=PROMPT)

        memory = ConversationBufferWindowMemory(
            k=5, memory_key="chat_history", return_messages=True, output_key="answer"
        )

        for i in range(0, int(len(chat_history) / 2)):
            memory.save_context(
                {"input": chat_history[i * 2]}, {"answer": chat_history[(i * 2) + 1]}
            )
        chain = ConversationalRetrievalChain(
            retriever=vector_store.as_retriever(),
            combine_docs_chain=doc_chain,
            question_generator=question_generator,
            memory=memory,
            return_source_documents=True,
        )

        result = chain({"question": user_question})
        run_id = str(cb.traced_runs[0].id)
        return result, run_id
```

### Description

I am trying to use langchain with Azure Search

### System Info

I am using the following libraries:

langchain==0.1.0
langsmith==0.0.83
langchainhub==0.1.14
langchain-community==0.0.12
langchain-openai==0.0.3
azure-search-documents==11.4.0
openai==1.7.2
azure-identity == 1.13.0
azure-core ==1.28.0

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by levalencia** [comment]
yes, downgrading works, but I expect somebody can fix this dependency to use the latest stable release by MIcrosoft.
