### ISSUE TITLE
AttributeError: 'Collection' object has no attribute 'model_fields'

### ISSUE THREAD

**Issue by MinhHoan147** [langchain-ai/langchain#24163]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
def create_selector():
    try:
        vectorstore = Chroma()
        vectorstore.delete_collection()
        selector = SemanticSimilarityExampleSelector.from_examples(
            examples,
            llm_embeddings,
            vectorstore,
            k=1,
            input_keys=["input"],
        )
        return selector
    except Exception as e:
        logger.error(e)
        return None
```

### Error Message and Stack Trace (if applicable)

'Collection' object has no attribute 'model_fields'

### Description

I'm trying to use Chroma vectorstore in Langchain, and receive the error above. Error appeared when calling `Chroma()` function. 

### System Info

OS: Ubuntu
OS Version: Ubuntu 22.04
Python Version: 3.10.12 

### Packages
langchain==0.2.5
langchain-chroma==0.1.2
langchain_community==0.2.5
langchain-openai==0.1.8

**Comment by lingvisa** [comment]
I am on Mac and having the same issue.

**Comment by mbastian** [comment]
Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

**Comment by MinhHoan147** [comment]
> Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

Thanks @mbastian for the solution, it worked for me also.

**Comment by wiseman** [comment]
If this is a bug in chromadb 0.5.4 should it remain open?

**Comment by DevBhuyan** [comment]
> Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

It finally worked for me too. Thanks!

**Comment by erdult** [comment]
same problem with 0.5.4 in windows

**Comment by SandeshSawant19** [comment]
worked for me too. Thanks Buddy :)

**Comment by Balaji-Kartheek** [comment]
> Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

I'm still facing the same issue with 0.5.3 version as well

**Comment by lzxzy** [comment]
> > Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.
> 
> I'm still facing the same issue with 0.5.3 version as well

Same error for chromadb 0.5.3 , I'm using MAC M3

**Comment by chozillla** [comment]
Same issue even when downgrading, and I am working on Databricks.

**Comment by flavienbwk** [comment]
> > Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.
> 
> Thanks @mbastian for the solution, it worked for me also.

Hi, could you reopen the issue ? This should be fixed by the langchain team as it is a bug :)

**Comment by bruhacsA** [comment]
This is a bug with chromadb it seems... versions 0.5.5 and 0.5.4 both don't work and throw this error when starting a new collection, but version 0.5.3 does. I am using llama-index, not langchain, so I don't think this is a bug with langchain.

**Comment by JACKEYED** [comment]
same problem with 0.5.5 in windows
version 0.5.3 does

**Comment by JoseGHdz** [comment]
I encountered this issue with LlamaIndex and the downgrade also worked for me. Thanks for the fix!

**Comment by Harshitnitw** [comment]
> > Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.
> 
> I'm still facing the same issue with 0.5.3 version as well

I was also facing the issue, then restarting the kernel and then running all the cells in my ipynb file worked for me, after downgrading chromadb to 0.5.3 version

**Comment by phlin0424** [comment]
it works on me too. thanks!

**Comment by llm-learner** [comment]
same problem with 0.5.5 in windows
i tired chroma==0.5.4 ,0.5.3,0.5.1, stopped kernel and reran jupyter,,,have no idea......

**Comment by ITSAIDI** [comment]
> Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

Thanks man

**Comment by karthikcs** [comment]
> Downgrading to chromadb==0.5.3 worked for me. The 0.5.4 version was released yesterday.

Worked for me too.. Please fix it asap

**Comment by cc17** [comment]
It seems that this is the error version of the chromadb .I saw you guys can work with the chromadb==0.5.3,but I also can't work with the langchain.
this is my code:

from langchain_chroma import Chroma
vectorstore = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings(),
)

and it will cause the same error like this:
AttributeError: 'Collection' object has no attribute 'model_fields'

how should I do can resolve this problem?thx.

**Comment by maxw1489** [comment]
@cc17 This worked for me using chromadb==0.5.3
![image](https://github.com/user-attachments/assets/fd275fae-67dc-4f6f-adca-bdc24664ef1d)

**Comment by cc17** [comment]
> @cc17 This worked for me using chromadb==0.5.3 ![image](https://private-user-images.githubusercontent.com/72010304/360398247-fd275fae-67dc-4f6f-adca-bdc24664ef1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzU1NTgsIm5iZiI6MTcyNDgzNTI1OCwicGF0aCI6Ii83MjAxMDMwNC8zNjAzOTgyNDctZmQyNzVmYWUtNjdkYy00ZjZmLWFkY2EtYmRjMjQ2NjRlZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4NTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNTYwYTU4YzU2NTEyOTYxNmE4NmZiZTg0YWJmMWFkYzVkNjQyZDljYjVlOTZjZDViNjlhMDhmZjY3ZTNlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MT_mmsavata0zI2h0RKUTau-WD14_AMx7AUnv9yMiGo)

it works,thx.

**Comment by lumiduque** [comment]
same issue when using chromadb on Sagemaker - had to downgrade

**Comment by Prathameshchakote** [comment]
downgrade work for me also on mac

**Comment by quadcube** [comment]
Downgrade to 0.5.1 works for me on Windows.
