### ISSUE TITLE
AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel'

### ISSUE THREAD

**Issue by rahulrajpv** [langchain-ai/langchain#14724]
### System Info

Similar issue, when tried to work with Gemini.Ai

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel'

### Expected behavior

just loaded those images that i have uploaded for the prompt

**Comment by haseeb-heaven** [comment]
Its Solved on Google Colab now and Replit IDE.

Here is [working demo of Python SDK on Google Colab](
https://colab.research.google.com/drive/1qAkS6YwMcRl52CHTM6g8FkZm9jrI9GPK?usp%3Dsharing):

**Comment by icewalf** [comment]
use : !pip install google-generativeai
not: !pip install google-generativelanguage

**Comment by feranzie** [comment]
if you're using a python version <3.9 that's why, I just changed my environment to one with version 3.10 and reinstalled  the package and it  works fine.

**Comment by haseeb-heaven** [comment]
Yea doesn’t work with Python 3.10 and above

**Comment by baskaryan** [comment]
duplicate of #14711

**Comment by leungyiuhoi** [comment]
python version  = or < 3.9

**Comment by imprasukjain** [comment]
I have the same issue, I am trying with the local machine and my Python configuration is 3.10.4, but it is still not working.......does it only work on Google Colab?
Any fixes or suggestions?

**Comment by haseeb-heaven** [comment]
> I have the same issue, I am trying with the local machine and my Python configuration is 3.10.4, but it is still not working.......does it only work on Google Colab? Any fixes or suggestions?

Use Virtual environment with Python 3.10 its works tested
