### ISSUE TITLE
AttributeError: 'OpenAIEmbeddings' object has no attribute 'embedding_ctx_length'

### ISSUE THREAD

**Issue by Sohojoe** [langchain-ai/langchain#1100]
since updating to v0.88 i get this error

```AttributeError: 'OpenAIEmbeddings' object has no attribute 'embedding_ctx_length```

Note: my faiss data and doc.index where create with an older version

my code is simple.
```
    index = faiss.read_index("docs.index")

    with open("faiss_store.pkl", "rb") as f:
        store = pickle. Load(f)
    store. Index = index
    
    docs = store.similarity_search_with_score(
            prompt, k=4
    )
```

it looks like it is releated to this PR [https://github.com/hwchase17/langchain/pull/991](https://github.com/hwchase17/langchain/pull/991) by @Hase-U

**Comment by Hase-U** [comment]
https://github.com/hwchase17/langchain/pull/1101

**Comment by Hase-U** [comment]
@Sohojoe 
I excluded codes that guarantee backward compatibility according to [langchain's policy](https://github.com/hwchase17/langchain/pull/1101).
However, this problem can be avoided by using hasattr like [this](
https://github.com/hwchase17/langchain/pull/1101/commits/79f8ee1ba49ab0ea324bdb9aaea1d83f87980baf)
