### ISSUE TITLE
Tools with args_schema dict cannot get ToolRuntime or injected parameter

### ISSUE THREAD

**Issue by sardismart** [langchain-ai/langchain#34293]
### Checked other resources

- [x] This is a bug, not a usage question.
- [x] I added a clear and descriptive title that summarizes this issue.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
- [x] This is not related to the langchain-community package.
- [x] I posted a self-contained, minimal, reproducible example. A maintainer can copy it and run it AS IS.

### Package (Required)

- [x] langchain
- [ ] langchain-openai
- [ ] langchain-anthropic
- [ ] langchain-classic
- [x] langchain-core
- [ ] langchain-cli
- [ ] langchain-model-profiles
- [ ] langchain-tests
- [ ] langchain-text-splitters
- [ ] langchain-chroma
- [ ] langchain-deepseek
- [ ] langchain-exa
- [ ] langchain-fireworks
- [ ] langchain-groq
- [ ] langchain-huggingface
- [ ] langchain-mistralai
- [ ] langchain-nomic
- [ ] langchain-ollama
- [ ] langchain-perplexity
- [ ] langchain-prompty
- [ ] langchain-qdrant
- [ ] langchain-xai
- [ ] Other / not sure / general

### Example Code (Python)

```python
from typing import Annotated, Dict, Any
from pydantic import BaseModel, create_model

from langchain_core.messages import HumanMessage
from langchain.tools import tool, ToolRuntime, InjectedToolCallId
from langchain_openai import ChatOpenAI
from langchain.chat_models import init_chat_model
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from typing_extensions import TypedDict
import os


weather_schema = {
    "type": "object",
    "properties": {
        "location": {"type": "string"},
        "units": {"type": "string"},
        "include_forecast": {"type": "boolean"},
    },
    "required": ["location", "units", "include_forecast"]
}

@tool(args_schema=weather_schema)
def get_weather(runtime: ToolRuntime = None, **kargs) -> str:
    """Get current weather and optional forecast."""
    print(f"injected runtime: {runtime}")
    print(f"kargs: {kargs}")
    units = kargs["units"]
    location = kargs["location"]
    include_forecast = kargs["include_forecast"]
    temp = 22 if units == "celsius" else 72
    result = f"Current weather in {location}: {temp} degrees {units[0].upper()}"
    if include_forecast:
        result += "\nNext 5 days: Sunny"
    return result


# Define agent state
class AgentState(TypedDict):
    messages: Annotated[list, add_messages]


# Create tools list
tools = [get_weather]


def create_weather_agent():
    """Create a LangGraph agent with weather tool."""
    # Initialize LLM with tools
    llm = init_chat_model("gpt-4o")
    llm_with_tools = llm.bind_tools(tools=tools)

    # Define agent node
    def agent_node(state: AgentState):
        response = llm_with_tools.invoke(state["messages"])
        return {"messages": [response]}

    # Define routing logic
    def should_continue(state: AgentState):
        last_message = state["messages"][-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tools"
        return END

    # Build the graph
    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("agent", agent_node)
    workflow.add_node("tools", ToolNode(tools))

    # Add edges
    workflow.add_edge(START, "agent")
    workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
    workflow.add_edge("tools", "agent")

    return workflow.compile()


async def main():
    """Run the weather agent."""
    agent = create_weather_agent()

    # Test query
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content="What's the weather in Tokyo? Include forecast")]}
    )

    for msg in result["messages"]:
        print(f"{msg.__class__.__name__}: {msg.content}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

### Error Message and Stack Trace (if applicable)

```shell

```

### Description

I was trying to create a tool with tool decorator and args_schema and would like to access ToolRuntime.
But the ToolRuntime does not inject into the tool and got None object when invoke tool.
>injected runtime: None

Besides, the parameter like tool call id with Annotation InjectedToolCallId also not work.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 25.1.0: Mon Oct 20 19:34:03 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T8112
> Python Version:  3.13.6 (main, Aug  8 2025, 16:50:55) [Clang 20.1.4 ]

Package Information
-------------------
> langchain_core: 1.1.3
> langchain: 1.1.3
> langsmith: 0.4.44
> langchain_mcp_adapters: 0.2.1
> langchain_openai: 1.0.3
> langchain_tavily: 0.2.13
> langgraph_api: 0.4.28
> langgraph_cli: 0.4.7
> langgraph_runtime_inmem: 0.14.1
> langgraph_sdk: 0.2.9

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.12.15
> blockbuster: 1.5.25
> click: 8.3.1
> cloudpickle: 3.1.2
> cryptography: 44.0.3
> httpx: 0.28.1
> jsonpatch: 1.33
> jsonschema-rs: 0.29.1
> langgraph: 1.0.4
> langgraph-checkpoint: 3.0.1
> mcp: 1.21.2
> openai: 2.8.1
> opentelemetry-api: 1.34.1
> opentelemetry-exporter-otlp-proto-http: 1.34.1
> opentelemetry-sdk: 1.34.1
> orjson: 3.11.4
> packaging: 25.0
> pydantic: 2.12.4
> pyjwt: 2.10.1
> pytest: 9.0.1
> python-dotenv: 1.2.1
> pyyaml: 6.0.3
> requests: 2.32.5
> requests-toolbelt: 1.0.0
> rich: 14.2.0
> sse-starlette: 2.1.3
> starlette: 0.50.0
> structlog: 25.5.0
> tenacity: 9.1.2
> tiktoken: 0.12.0
> truststore: 0.10.4
> typing-extensions: 4.15.0
> uuid-utils: 0.12.0
> uvicorn: 0.36.0
> watchfiles: 1.1.1
> zstandard: 0.25.0

**Comment by keenborder786** [comment]
Just change `runtime: ToolRuntime = None` to `runtime: ToolRuntime`, no default value of None. It will work.

**Comment by sardismart** [comment]
> Just change `runtime: ToolRuntime = None` to `runtime: ToolRuntime`, no default value of None. It will work.

This will bring exception: 
```
Traceback (most recent call last):
  File "/Users/sardismart/git/test-langchain-tool/app/test.py", line 104, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/Users/sardismart/.local/share/uv/python/cpython-3.13.6-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Users/sardismart/.local/share/uv/python/cpython-3.13.6-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/sardismart/.local/share/uv/python/cpython-3.13.6-macos-aarch64-none/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/sardismart/git/test-langchain-tool/app/test.py", line 93, in main
    result = await agent.ainvoke(
             ^^^^^^^^^^^^^^^^^^^^
        {"messages": [HumanMessage(content="What's the weather in Tokyo? Include forecast")]}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/pregel/main.py", line 3158, in ainvoke
    async for chunk in self.astream(
    ...<29 lines>...
            chunks.append(chunk)
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/pregel/main.py", line 2971, in astream
    async for _ in runner.atick(
    ...<13 lines>...
            yield o
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/pregel/_runner.py", line 304, in atick
    await arun_with_retry(
    ...<15 lines>...
    )
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/pregel/_retry.py", line 137, in arun_with_retry
    return await task.proc.ainvoke(task.input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/_internal/_runnable.py", line 705, in ainvoke
    input = await asyncio.create_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
        step.ainvoke(input, config, **kwargs), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/_internal/_runnable.py", line 473, in ainvoke
    ret = await self.afunc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 760, in _afunc
    outputs = await asyncio.gather(*coros)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 1099, in _arun_one
    return await self._execute_tool_async(tool_request, input_type, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 1048, in _execute_tool_async
    content = _handle_tool_error(e, flag=self._handle_tool_errors)
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 404, in _handle_tool_error
    content = flag(e)  # type: ignore [assignment, call-arg]
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 361, in _default_handle_tool_errors
    raise e
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langgraph/prebuilt/tool_node.py", line 1001, in _execute_tool_async
    response = await tool.ainvoke(call_args, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/tools/structured.py", line 64, in ainvoke
    return await run_in_executor(config, self.invoke, input, config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/runnables/config.py", line 608, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/Users/sardismart/.local/share/uv/python/cpython-3.13.6-macos-aarch64-none/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/runnables/config.py", line 599, in wrapper
    return func(*args, **kwargs)
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/tools/base.py", line 605, in invoke
    return self.run(tool_input, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/tools/base.py", line 932, in run
    raise error_to_raise
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/tools/base.py", line 898, in run
    response = context.run(self._run, *tool_args, **tool_kwargs)
  File "/Users/sardismart/git/test-langchain-tool/.venv/lib/python3.13/site-packages/langchain_core/tools/structured.py", line 93, in _run
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: get_weather() missing 1 required positional argument: 'runtime'
During task with name 'tools' and id '0d0d7005-b9da-efcb-442d-079f17656155'
```

**Comment by keenborder786** [comment]
@sardismart , please see the following:
```python


weather_schema = {
    "type": "object",
    "properties": {
        "location": {"type": "string"},
        "units": {"type": "string"},
        "include_forecast": {"type": "boolean"},
    },
    "required": ["location", "units", "include_forecast"]
}

@tool(args_schema=weather_schema)
def get_weather(runtime: ToolRuntime, **kargs) -> str:
    """Get current weather and optional forecast."""
    print(f"injected runtime: {runtime}")
    print(f"kargs: {kargs}")
    units = kargs["units"]
    location = kargs["location"]
    include_forecast = kargs["include_forecast"]
    temp = 22 if units == "celsius" else 72
    result = f"Current weather in {location}: {temp} degrees {units[0].upper()}"
    if include_forecast:
        result += "\nNext 5 days: Sunny"
    return result


# Define agent state
class AgentState(TypedDict):
    messages: Annotated[list, add_messages]


# Create tools list
tools = [get_weather]


def create_weather_agent():
    """Create a LangGraph agent with weather tool."""
    # Initialize LLM with tools
    llm = init_chat_model("gpt-4o")
    llm_with_tools = llm.bind_tools(tools=tools)

    # Define agent node
    def agent_node(state: AgentState):
        response = llm_with_tools.invoke(state["messages"])
        return {"messages": [response]}

    # Define routing logic
    def should_continue(state: AgentState):
        last_message = state["messages"][-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tools"
        return END

    # Build the graph
    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("agent", agent_node)
    workflow.add_node("tools", ToolNode(tools))

    # Add edges
    workflow.add_edge(START, "agent")
    workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
    workflow.add_edge("tools", "agent")

    return workflow.compile()


async def main():
    """Run the weather agent."""
    agent = create_weather_agent()

    # Test query
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content="What's the weather in Tokyo? Include forecast")]}
    )

    for msg in result["messages"]:
        print(f"{msg.__class__.__name__}: {msg.content}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())


```

**Comment by sardismart** [comment]
Hi @keenborder786 
Could you show your output?
I still got exception with
>TypeError: get_weather() missing 1 required positional argument: 'runtime'

**Comment by sydney-runkle** [comment]
I'm not able to repro w/

```py
from typing import Annotated

from typing_extensions import TypedDict

from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage
from langchain_core.tools import tool
from langchain.tools import ToolRuntime
from langgraph.graph import END, START, StateGraph, add_messages
from langgraph.prebuilt import ToolNode


weather_schema = {
    "type": "object",
    "properties": {
        "location": {"type": "string"},
        "units": {"type": "string"},
        "include_forecast": {"type": "boolean"},
    },
    "required": ["location", "units", "include_forecast"]
}

@tool(args_schema=weather_schema)
def get_weather(runtime: ToolRuntime | None = None, **kargs) -> str:
    """Get current weather and optional forecast."""
    print(f"injected runtime: {runtime}")
    print(f"kargs: {kargs}")
    units = kargs["units"]
    location = kargs["location"]
    include_forecast = kargs["include_forecast"]
    temp = 22 if units == "celsius" else 72
    result = f"Current weather in {location}: {temp} degrees {units[0].upper()}"
    if include_forecast:
        result += "\nNext 5 days: Sunny"
    return result


# Define agent state
class AgentState(TypedDict):
    messages: Annotated[list, add_messages]


# Create tools list
tools = [get_weather]


def create_weather_agent():
    """Create a LangGraph agent with weather tool."""
    # Initialize LLM with tools
    llm = init_chat_model("gpt-4o")
    llm_with_tools = llm.bind_tools(tools=tools)

    # Define agent node
    def agent_node(state: AgentState):
        response = llm_with_tools.invoke(state["messages"])
        return {"messages": [response]}

    # Define routing logic
    def should_continue(state: AgentState):
        last_message = state["messages"][-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tools"
        return END

    # Build the graph
    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("agent", agent_node)
    workflow.add_node("tools", ToolNode(tools))

    # Add edges
    workflow.add_edge(START, "agent")
    workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
    workflow.add_edge("tools", "agent")

    return workflow.compile()


async def main():
    """Run the weather agent."""
    agent = create_weather_agent()

    # Test query
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content="What's the weather in Tokyo? Include forecast")]}
    )

    for msg in result["messages"]:
        print(f"{msg.__class__.__name__}: {msg.content}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

or 

```
runtime: ToolRuntime | None = None
```

Going to mark as closed for now, if you have a MRE on latest, happy to TAL!

**Comment by sardismart** [comment]
Resolved after upgrade langgraph-prebuilt from 1.0.4 to 1.0.5

**Comment by denvasylenko** [comment]
Have the same issue with the same setup... 

missing 1 required positional argument: 'runtime'
