### PR TITLE
chore: revert #16608

### LINKED ISSUE #16962: Qdrant: Performing a similarity search results in an "AttributeError"
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

The code from the [Qdrant documentation](https://python.langchain.com/docs/integrations/vectorstores/qdrant) shows the error:

```python
from dotenv import load_dotenv

from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import Qdrant
from langchain_openai import OpenAIEmbeddings

load_dotenv()

loader = TextLoader("../../modules/state_of_the_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

qdrant = Qdrant.from_documents(
    docs,
    embeddings,
    location=":memory:",  # Local mode with in-memory storage only
    collection_name="my_documents",
)

query = "What did the president say about Ketanji Brown Jackson"
found_docs = qdrant.similarity_search(query)

print(found_docs[0].page_content)
```

The only adjustment here was how to set the `OPENAI_API_KEY` value (any mechanism works).

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\sfitts\GitHub\ag2rs\modelmgr\src\main\python\qdrant_example.py", line 26, in <module>
    found_docs = qdrant.similarity_search(query)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sfitts\.virtualenvs\semanticsearch\Lib\site-packages\langchain_community\vectorstores\qdrant.py", line 286, in similarity_search
    results = self.similarity_search_with_score(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sfitts\.virtualenvs\semanticsearch\Lib\site-packages\langchain_community\vectorstores\qdrant.py", line 362, in similarity_search_with_score
    return self.similarity_search_with_score_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sfitts\.virtualenvs\semanticsearch\Lib\site-packages\langchain_community\vectorstores\qdrant.py", line 620, in similarity_search_with_score_by_vector
    return [
           ^
  File "C:\Users\sfitts\.virtualenvs\semanticsearch\Lib\site-packages\langchain_community\vectorstores\qdrant.py", line 622, in <listcomp>
    self._document_from_scored_point(
  File "C:\Users\sfitts\.virtualenvs\semanticsearch\Lib\site-packages\langchain_community\vectorstores\qdrant.py", line 1946, in _document_from_scored_point
    metadata["_collection_name"] = scored_point.collection_name
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ScoredPoint' object has no attribute 'collection_name'
python-BaseException

Process finished with exit code 1
```

### Description

I'm trying to use Qdrant to perform similarity searches as part of a RAG chain.  This was working fine in `langchain-community==0.0.16`, but produces the error above in `langchain-community==0.0.17`.  The source of the break is this PR -- https://github.com/langchain-ai/langchain/pull/16608.  While it would be nice to have access to the collection name, the QDrant class `ScoredPoint` does not have the referenced property (and AFAICT never has).

### System Info

```
System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.18
> langchain: 0.1.4
> langchain_community: 0.0.17
> langchain_openai: 0.0.5
> langserve: 0.0.41

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
```

Note that the failure was originally found using `langchain==0.1.5`.

### PR DESCRIPTION
**Pull request by Anush008**
## Description

Reverts #16608 to resolve the`AttributeError: 'ScoredPoint' object has no attribute 'collection_name'` issue.
Fixes #16962.

### CODE REVIEW

**Comment by Anush008** [comment]
Will be resolved by #16920.
