### ISSUE TITLE
OpenAIEmbeddings() does not work because of these bugs

### ISSUE THREAD

**Issue by pranavgupta2603** [langchain-ai/langchain#12943]
### System Info

Python Version: 3.11
LangChain Version: 0.0.331
OpenAI Version: 1.0.0

### Who can help?

@hwchase17, @agola11, @eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The following error has been caused due to the recent change in version of OpenAI to 1.0.0
**Use OpenAI==0.28.1 to fix this error**
With the code:
`embeddings = OpenAIEmbeddings()`

The error produced is:
`AttributeError: module 'openai' has no attribute 'Embedding'. Did you mean: 'embeddings'?`

I went through the `langchain/embeddings/openai.py` file and then changed `value["client"] = openai.Embedding` to `value["client"] = openai.embeddings`, but then I receive this new error:

`AttributeError: module 'openai' has no attribute 'error'` in the same file (`langchain/embeddings/openai.py`)

### Expected behavior

There should be no error when calling this function.

**Comment by alexyoung23jj** [comment]
Same error

**Comment by RRaffay** [comment]
Facing the same issue. Wonder if they announce something in the summit

**Comment by luccafabro** [comment]
Same error here, waiting solution...

**Comment by georgetok** [comment]
Same error

**Comment by tasansal** [comment]
this only happens with the latest `openai-python`. Probably breaking changes on the API as a workaround at the moment. Langchain will probably need updates to support major version change.

**Comment by RRaffay** [comment]
Docs just updated:

```
from openai import OpenAI
client = OpenAI()

def get_embedding(text, model="text-embedding-ada-002"):
   text = text.replace("\n", " ")
   return client.embeddings.create(input = [text], model=model)['data'][0]['embedding']
```

Probably need to initialize the client instead of using `openai.embeddings `

**Comment by beongeist** [comment]
> Docs just updated:
> 
> ```
> from openai import OpenAI
> client = OpenAI()
> 
> def get_embedding(text, model="text-embedding-ada-002"):
>    text = text.replace("\n", " ")
>    return client.embeddings.create(input = [text], model=model)['data'][0]['embedding']
> ```
> 
> Probably need to initialize the client instead of using `openai.embeddings `

Do you have an example of how to replace the original code: ```embeddings = OpenAIEmbeddings()```

**Comment by rbuck-som** [comment]
> Same error

same issue here

**Comment by RRaffay** [comment]
@beongeist haven't gotten around to looking too deeply into it but I assume you'd need to override the OpenAIEmbeddings class. @dosubot's answer might be good starting point but I'm not sure if there are other dependencies that it might mess up. You could also just try using an older version of the openai library if that's still working. 

```
class OpenAIEmbeddings(BaseEmbeddings):
    def __init__(self, openai_api_key, model="davinci", max_tokens=4096, max_retries=3):
        super().__init__(openai_api_key, model, max_tokens, max_retries)
        self.client = openai.embeddings  # updated attribute

    def _handle_error(self, error):
        if isinstance(error, openai.NewErrorName):  # updated attribute
            # handle error
            pass
        else:
            # handle other errors
            pass
```

**Comment by georgetok** [comment]
pip install openai==0.28.1 as a hotfix works, guys

**Comment by valvesss** [comment]
same error! fucked my prod lol

**Comment by hwchase17** [comment]
yup we're working on moving to support 1.x releases, but for now please pin `openai==0.28.1` - sorry!

**Comment by criolho** [comment]
Same here, still getting the error:

(openai) # pip list | grep openai
openai           1.1.1

(openai) # python
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from langchain.embeddings import OpenAIEmbeddings
>>> from langchain.vectorstores import Chroma
>>> vectorstore = Chroma.from_texts(["Harrison worked at Kensho"], embedding=OpenAIEmbeddings())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/bin/test/openai/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/test/openai/lib/python3.11/site-packages/pydantic/v1/main.py", line 1050, in validate_model
    input_data = validator(cls_, input_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/test/openai/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 284, in validate_environment
    values["client"] = openai.Embedding
                       ^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'Embedding'. Did you mean: 'embeddings'?

**Comment by efriis** [comment]
I'll wait to close this until after a release is cut! This will be in 0.0.332

**Comment by efriis** [comment]
While release is getting worked on, you can do
```
pip install langchain==0.0.331rc2 chromadb==0.4.15
```

I included the chromadb lock on 0.4.15 because their team is also working on addressing a change in 0.4.16 that would also break your code! https://github.com/langchain-ai/langchain/issues/13051#issuecomment-1801478715

**Comment by efriis** [comment]
Langchain 0.0.332 released with the chroma team's fix for compatibility with chromadb>=0.4.16

Can now use latest of both `pip install -U langchain chromadb`
