### ISSUE TITLE
AttributeError: 'PGVector' object has no attribute 'CollectionStore'. Did you mean: 'collection_name'?

### ISSUE THREAD

**Issue by anirbanpuky** [langchain-ai/langchain#12629]
### System Info

Langchain version. - 0.0.326
Python - 3.9.6

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

embeddings = HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2')
CONNECTION_STRING = "postgresql+psycopg2://hwc@localhost:5432/test3"
COLLECTION_NAME = "state_of_the_union_test"

vectorestore = PGVector.from_documents(
                embedding=embeddings,
                documents=docs,
                collection_name=COLLECTION_NAME,
                connection_string=CONNECTION_STRING,
            )

Getting below error 

line 221, in get_collection
    return self.CollectionStore.get_by_name(session, self.collection_name)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PGVector' object has no attribute 'CollectionStore'. Did you mean: 'collection_name'?

### Expected behavior

The embeddings should be stored in the database using pgvector.

**Comment by gregdrizz** [comment]
seems like they deleted __post_init__ by mistake see issue:
https://github.com/langchain-ai/langchain/issues/12616

**Comment by anirbanpuky** [comment]
After I downgraded my version to 0.0.229, it is working. So Fix is needed for latest versions.

**Comment by gregdrizz** [comment]
upgrading to 0.0.327 didn't fix it either. only downgrading worked.

**Comment by nitinramvelraj** [comment]
Also facing same issue with 0.0.327

**Comment by deniercounter** [comment]
Can confirm the above mentioned error:

**AttributeError: 'PGVector' object has no attribute 'CollectionStore'**

with langchain version 0.0.327 and Python 3.9.18

definitely worked with version 0.0.315

**Comment by deniercounter** [comment]
> Can confirm the above mentioned error:
> 
> **AttributeError: 'PGVector' object has no attribute 'CollectionStore'**
> 
> with langchain version 0.0.327 and Python 3.9.18
> 
> definitely worked with version 0.0.315

I can confirm that with the upgrade to v0.0.329 this problem is SOLVED.
