### ISSUE TITLE
`AttributeError: 'ChatCompletion' object has no attribute 'citations'` when using `langchain_perplexity.chat_model.ChatPerplexity` with model 'r1-1776'

### ISSUE THREAD

**Issue by ch-amal0** [langchain-ai/langchain#30767]
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
- [x] I posted a self-contained, minimal, reproducible example. A maintainer can copy it and run it AS IS.

### Example Code

The following code : 

```python
from langchain_core.messages import HumanMessage
from langchain_perplexity.chat_models import ChatPerplexity

llm = ChatPerplexity(
    model='r1-1776'
)

response = llm.invoke([HumanMessage("How many stars are there in the sky ?")])

print(response)
```

Does not work with version 0.1 of `langchain_perplexity`

### Error Message and Stack Trace (if applicable)

AttributeError: 'ChatCompletion' object has no attribute 'citations'

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 11
      5 from langchain_perplexity.chat_models import ChatPerplexity
      7 llm = ChatPerplexity(
      8     model='r1-1776'
      9 )
---> 11 response = llm.invoke([HumanMessage("How many stars are there in the sky ?")])
     13 print(response)
     14 print(response.usage_metadata)

File ~/.../lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:331, in BaseChatModel.invoke(self, input, config, stop, **kwargs)
    319 @override
    320 def invoke(
    321     self,
   (...)    326     **kwargs: Any,
    327 ) -> BaseMessage:
    328     config = ensure_config(config)
    329     return cast(
    330         "ChatGeneration",
--> 331         self.generate_prompt(
    332             [self._convert_input(input)],
    333             stop=stop,
    334             callbacks=config.get("callbacks"),
    335             tags=config.get("tags"),
    336             metadata=config.get("metadata"),
    337             run_name=config.get("run_name"),
    338             run_id=config.pop("run_id", None),
    339             **kwargs,
    340         ).generations[0][0],
    341     ).message

File ~/.../lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:894, in BaseChatModel.generate_prompt(self, prompts, stop, callbacks, **kwargs)
    885 @override
    886 def generate_prompt(
    887     self,
   (...)    891     **kwargs: Any,
    892 ) -> LLMResult:
    893     prompt_messages = [p.to_messages() for p in prompts]
--> 894     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)

File ~/.../lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:719, in BaseChatModel.generate(self, messages, stop, callbacks, tags, metadata, run_name, run_id, **kwargs)
    716 for i, m in enumerate(messages):
    717     try:
    718         results.append(
--> 719             self._generate_with_cache(
    720                 m,
    721                 stop=stop,
    722                 run_manager=run_managers[i] if run_managers else None,
    723                 **kwargs,
    724             )
    725         )
    726     except BaseException as e:
    727         if run_managers:

File ~/.../lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:960, in BaseChatModel._generate_with_cache(self, messages, stop, run_manager, **kwargs)
    958 else:
    959     if inspect.signature(self._generate).parameters.get("run_manager"):
--> 960         result = self._generate(
    961             messages, stop=stop, run_manager=run_manager, **kwargs
    962         )
    963     else:
    964         result = self._generate(messages, stop=stop, **kwargs)

File ~/.../lib/python3.11/site-packages/langchain_perplexity/chat_models.py:391, in ChatPerplexity._generate(self, messages, stop, run_manager, **kwargs)
    388 else:
    389     usage_metadata = None
--> 391 additional_kwargs = {"citations": response.citations}
    392 for attr in ["images", "related_questions"]:
    393     if hasattr(response, attr):

File ~/.../lib/python3.11/site-packages/pydantic/main.py:994, in BaseModel.__getattr__(self, item)
    991     return super().__getattribute__(item)  # Raises AttributeError if appropriate
    992 else:
    993     # this is the current error
--> 994     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'ChatCompletion' object has no attribute 'citations'
```

### Description

Using the Perplexity module of langchain to interact with Perplexity API, the reasoning model `r1-1776` throws the error `AttributeError: 'ChatCompletion' object has no attribute 'citations'`.

This is likely due to the fact that this model is an offline one, so does not access the perplexity search engine or the web, meaning the model does not have any citations to return.

But `langchain_perplexity.chat_models.ChatPerplexity` is always looking for the citations attribute in the response object after calling `ChatPerplexity.invoke(....)`   (line 391 of ChatPerplexity file is `additional_kwargs = {"citations": response.citations}` with no error handling or default value in case no citations).

### System Info

Ubuntu v22.04 through WSL 2 , Python 3.11, langchain-perplexity v0.1.0
