### PR TITLE
Fix AttributeError _client_settings

### LINKED ISSUE #7482: AttributeError: 'Chroma' object has no attribute '_client_settings'
### System Info

on Python 3.10.10

with requirements.txt 
```
pandas==2.0.1
beautifulsoup4==4.12.2
langchain==0.0.229
chromadb==0.3.26
tiktoken==0.4.0
gradio==3.36.1
Flask==2.3.2
torch==2.0.1
sentence-transformers==2.2.2
``` 

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm getting `AttributeError: 'Chroma' object has no attribute '_client_settings'` when running

```python
from langchain.vectorstores import Chroma
import chromadb
from chromadb.config import Settings
from langchain.embeddings import HuggingFaceEmbeddings
from constants.model_constants import HF_EMBEDDING_MODEL

chroma_client = chromadb.Client(Settings(chroma_api_impl="rest", chroma_server_host="xxxxx", chroma_server_http_port="443", chroma_server_ssl_enabled=True))


embedder = HuggingFaceEmbeddings(
                model_name=HF_EMBEDDING_MODEL,
                model_kwargs={"device": "cpu"},
                encode_kwargs={'normalize_embeddings': False}
            )

chroma_vector_store = Chroma(
            collection_name="test",
            embedding_function=embedder,
            client=chroma_client)
``` 

the traceback is 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rubelagu/.pyenv/versions/3.10.10/envs/xxxxTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rubelagu/.pyenv/versions/3.10.10/envs/oraklet_chatbot/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 94, in __init__
    self._client_settings.persist_directory or persist_directory
AttributeError: 'Chroma' object has no attribute '_client_settings'/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 94, in __init__
    self._client_settings.persist_directory or persist_directory
AttributeError: 'Chroma' object has no attribute '_client_settings'
```
### Expected behavior

It should not raise an exception,

It seems to me that 
https://github.com/hwchase17/langchain/blob/5eec74d9a5435c671382e69412072a8725b2ec60/langchain/vectorstores/chroma.py#L93-L95

was introduced by commit https://github.com/hwchase17/langchain/commit/a2830e3056e4e616160b150bf5ea212a97df2dc4
from @nb-programmer   and @rlancemartin 

that commit assumes that self._client_settings exists always when in reality that won't be created if a client is passed

### PR DESCRIPTION
**Pull request by ecerulm**
Closes #7482 

@rlancemartin  @nb-programmer

### CODE REVIEW

**Comment by nb-programmer** [comment]
Yup I think this should fix the issue, and also solve @Buckler89 's issue

**Comment by huineng** [comment]
yes it will fix the issue (tested)

**Comment by nb-programmer** [comment]
@hwchase17 hey can you merge this fix? It fixes the issue caused by my "persist()" fix which was incomplete apparently

**Comment by ecerulm** [comment]
Yes, I guess  #7639 fixes it already.
