### ISSUE TITLE
'BedrockChat' object has no attribute 'bind_tools'

### ISSUE THREAD

**Issue by evandrofranco** [langchain-ai/langchain#19162]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import boto3
import json
from langchain_community.chat_models import BedrockChat
from langchain.agents import tool
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

boto3_bedrock = boto3.client('bedrock-runtime')
modelId = "anthropic.claude-3-sonnet-20240229-v1:0"

llm = BedrockChat(
    model_id=modelId, 
    client = boto3_bedrock
)

@tool
def get_word_length(word: str) -> int:
    """Returns the length of a word."""
    return len(word)

#get_word_length.invoke("abc")

tools = [get_word_length]

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are very powerful assistant, but don't know current events",
        ),
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)

llm_with_tools = llm.bind_tools(tools)
```

### Error Message and Stack Trace (if applicable)

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 llm_with_tools = llm.bind_tools(tools)

AttributeError: 'BedrockChat' object has no attribute 'bind_tools'
```

### Description

I am trying to follow [this](https://python.langchain.com/docs/modules/agents/how_to/custom_agent) guide with Bedrock and it's throwing this error.

### System Info

langchain==0.1.12
langchain-community==0.0.28
langchain-core==0.1.32
langchain-text-splitters==0.0.1

**Comment by tomdf-fortescue** [comment]
any updates on when/if this is going to be implemented?

**Comment by Neet-Nestor** [comment]
Any update? Clearly Bedrock API is currently supporting this but LangChain has not updated yet.

[Tool Calling](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html#model-parameters-anthropic-claude-messages-tool-use.title)

**Comment by rajidhamon31** [comment]
I am also facing the same issue, is it updated?

**Comment by cipher982** [comment]
I just updated langchain and tried again. It appears tool call are now working with `0.2.6`
