### ISSUE TITLE
Error with ChatVectorDBChain.from_llm on Hugging Face

### ISSUE THREAD

**Issue by ailanguageinnovations** [langchain-ai/langchain#1273]
Loving Langchain it's awesome! 

I have a Hugging Face project which is a clone of this one hwchase17/chat-your-data-state-of-the-union. 
This was all working fine on Langchain 0.0.86 but now I'm on 0.0.93 it doesn't, and I'm getting the following error:

File "/home/user/.local/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 107, in similarity_search_with_score_by_vector
    scores, indices = self.index.search(np.array([embedding], dtype=np.float32), k)
TypeError: search() missing 3 required positional arguments: 'k', 'distances', and 'labels'

If I run the app locally it's also working fine. I'm also on Python 3.8 for both envs. 

Any help is much appreciated!

**Comment by patrickstorm** [comment]
I don't know if this will help you, but I solved it by not uploading my pkl files. I added them to the .gitignore so they were forced to be recreated on the server and that solved this error for me 🤷

**Comment by thebotforge** [comment]
hey @patrickstorm, thanks for the tip, this actually worked for me as well! Thanks!

**Comment by mihaiblaga89** [comment]
having the same issue but for me generating the PKL there is not possible. Any ideas? Tried messing around with permissions/ownership, no luck.

**Comment by marianbastiUNRN** [comment]
Same here, sending a pkl generated on one machine over to another yielded that same error

**Comment by danielchalef** [comment]
`faiss-cpu` indexes are CPU arch-dependent. You can't build an index on `arm64` (a MacBook M-series) and deploy to a `amd64` server (most Intel and AMD-powered cloud services). As pointed out above, you'll need to build the index on the same arch as you deploy.

**Comment by Kr4us** [comment]
I have the same issue, tested on a Dell with Ubuntu 20.04 (Intel Core i7-10610U x86_64), EC2 t2.micro with Ubuntu 22.04 (Intel Xeon CPU E5-2676 v3 x86_64), Asus (Intel Core i7-8550U) and a Windows 10 desktop machine (Ryzen 9 5900x). Produced a vectorstore file in each machine with the same source data and each only work in their origin system. Always the same error.
Could there be any metadata on the embedding file?
